import streamlit as st
import json
import os
from datetime import datetime

# ================= 設定區 =================
DATA_FILE = "lunch_records_34.json"
DUTY_NEEDED = 9  # 每天需要抬飯的人數改為 9 人

# 行事曆特殊不吃午餐日期 (僅保留大學之旅、休業式、國定假日)
NO_LUNCH_DAYS = [
    "2026-09-25", # 中秋節放假
        "2026-10-10", # 國慶日
            "2026-11-13", "2026-11-14", "2026-11-15", # 高二大學之旅
                "2027-01-01", # 元旦
                    "2027-01-21"  # 休業式
                    ]
                    # ==========================================

                    def load_data():
                        if not os.path.exists(DATA_FILE):
                                # 預設的高二仁 34 人名單
                                        initial_students = [
                                                    {"seat": 1, "name": "凃真玲", "count": 0, "last_date": "2026-10-11"},
                                                                {"seat": 2, "name": "林昀儒", "count": 0, "last_date": "2026-10-11"},
                                                                            {"seat": 3, "name": "洪筠涵", "count": 0, "last_date": "2026-10-11"},
                                                                                        {"seat": 4, "name": "翁睿琳", "count": 0, "last_date": "2026-10-11"},
                                                                                                    {"seat": 5, "name": "高萱芳", "count": 0, "last_date": "2026-10-11"},
                                                                                                                {"seat": 6, "name": "高睿瑩", "count": 0, "last_date": "2026-10-11"},
                                                                                                                            {"seat": 7, "name": "陳姵羽", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                        {"seat": 8, "name": "陳宣羽", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                    {"seat": 9, "name": "陳雯妍", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                {"seat": 10, "name": "蔡喜恩", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                            {"seat": 11, "name": "蘇琬情", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                        {"seat": 12, "name": "蘇映羽", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                    {"seat": 13, "name": "賴楷沛", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                {"seat": 14, "name": "王浩宇", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                            {"seat": 15, "name": "江承育", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                        {"seat": 16, "name": "吳奕澔", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                    {"seat": 17, "name": "蕭佑倫", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                {"seat": 18, "name": "林亦均", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                            {"seat": 19, "name": "林冠廷", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                        {"seat": 20, "name": "林哲淵", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                    {"seat": 21, "name": "洪子睿", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                {"seat": 22, "name": "蔡沅峻", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                            {"seat": 23, "name": "郭羿靖", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                        {"seat": 24, "name": "陳芃宇", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                    {"seat": 25, "name": "蔡汶錡", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                {"seat": 26, "name": "陳宥廷", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                            {"seat": 27, "name": "陳家寶", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                        {"seat": 28, "name": "陳鈺昇", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                                    {"seat": 29, "name": "溫彥彬", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                                                {"seat": 30, "name": "黃子臣", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                                                            {"seat": 31, "name": "楊子頡", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                                                                        {"seat": 32, "name": "楊宇家", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"seat": 33, "name": "葛于宸", "count": 0, "last_date": "2026-10-11"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {"seat": 34, "name": "劉峻成", "count": 0, "last_date": "2026-10-11"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                save_data(initial_students)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return initial_students
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with open(DATA_FILE, "r", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return json.load(f)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def save_data(data):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(DATA_FILE, "w", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                json.dump(data, f, ensure_ascii=False, indent=2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.set_page_config(page_title="高二仁抬飯系統", page_icon="🍱")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.title("🍱 高二仁 午餐抬飯系統")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 1. 選擇日期
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target_date = st.date_input("選擇排班日期", datetime.now())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                date_str = target_date.strftime("%Y-%m-%d")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 2. 檢查特殊日
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if target_date.weekday() >= 5:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.info(f"【{date_str}】 是週末，不需要抬飯！")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.stop()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if date_str in NO_LUNCH_DAYS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.info(f"【{date_str}】 是特殊日（如國定假日/大學之旅），暫停輪值！")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.stop()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 3. 讀取資料
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                students = load_data()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 4. 下拉選單選擇請假人員
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.subheader("勾選今日請假/公假人員")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                student_options = [f"{s['seat']:02d}. {s['name']} (次數: {s['count']})" for s in students]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                absent_selections = st.multiselect("請選擇請假人員 (可輸入座號或姓名搜尋)：", student_options)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 提取請假座號
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                absent_seats = {int(sel.split(".")[0]) for sel in absent_selections}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 5. 產生按鈕
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if st.button("🚀 產生今日名單", type="primary"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    available = [s for s in students if s["seat"] not in absent_seats]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(available) < DUTY_NEEDED:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.warning(f"今天出席人數不足以抬飯！(需要 {DUTY_NEEDED} 人)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.stop()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                available.sort(key=lambda s: (s["count"], s["last_date"], s["seat"]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    selected = available[:DUTY_NEEDED]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        selected_seats = {s["seat"] for s in selected}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.success(f"🎉 【{date_str}】 抬飯名單 🎉")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for s in students:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if s["seat"] in selected_seats:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        s["count"] += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    s["last_date"] = date_str
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.write(f"👉 **座號 {s['seat']:02d} ({s['name']})** [累計: {s['count']}次]")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        save_data(students)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.balloons()

